AWSTemplateFormatVersion: 2010-09-09
Description: Checkpoint10 Paris Oui
Parameters:
  Name:
    Type: String
    Default: Saana
Resources:
  SaanaInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07eda9385feb1e969
      InstanceType: t2.nano
      SecurityGroups:
        - !Ref SaanaInstanceSecurityGroup
      Tags:
        - Key: Owner
          Value: !Ref Name
  SaanaInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Security group for Saanainstance'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
Outputs:
  PublicDNSName:
    Description: PublicDnsName of EC2
    Value: !GetAtt SaanaInstance.PublicDnsName


