AWSTemplateFormatVersion: 2010-09-09
Description: Checkpoint10 Paris Oui
Parameters:
  Name:
    Type: String
    Default: Saana
Resources:
  SaanaInstance:
    Type: AWS::EC2::Instance
    Properties:
      UserData:
        Fn::Base64:
          Fn::Join:
            - "\n"
            - - "#!/bin/bash"
              - "amazon-linux-extras install epel"
              - "amazon-linux-extras install nginx1"
              - "systemctl start nginx"
      ImageId: ami-07eda9385feb1e969
      InstanceType: t2.nano
      SecurityGroups:
        - !Ref SaanaInstanceSecurityGroup
      Tags:
        - Key: Owner
          Value: !Ref Name
  SaanaInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Security group for Saanainstance'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '80'
          ToPort: '80'
          CidrIp: 0.0.0.0/0
  SaananBucket:
    Type: AWS::S3::Bucket
    Properties:
      Tags:
        - Key: Owner
          Value: !Ref Name
  SaananSSM:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Value: !GetAtt SaananBucket.Arn

Outputs:
  PublicDNSName:
    Description: PublicDnsName of EC2
    Value: !GetAtt SaanaInstance.PublicDnsName


